version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8888:8888"

  backend:
    build:
      context: ./backend
    ports:
      - "5001:80"
      - "5000:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Users: "Host=db;Database=users;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      JWT__SECRET: "${JWT__SECRET}"
      JWT__AUDIENCE: "${JWT__AUDIENCE}"
      JWT__ISSUER: "${JWT__ISSUER}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.0-alpine
    container_name: ks-database
    ports:
      - "5432:5432"
    volumes:
      - ks_postgresql:/var/lib/postgresql/data
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER}'"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  ks_postgresql:
