version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8888:8888"
  backend:
    build:
      context: ./backend
    ports:
      - "5001:80"
      - "5000:443"
    environment:
      ConnectionStrings__Users: "Host=db;Database=Users;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      JWT__secret: "${JWT__secret}"
      JWT__audience: "${JWT__secret}"
      JWT__issuer: "${JWT__issuer}"
    depends_on:
      - "db"
  db:
    image: postgres:14.0-alpine
    ports:
      - "5432"
    volumes:
      - ks_postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
volumes:
  ks_postgresql: