services:
  apphost:
    build:
      context: .
      dockerfile: backend/AppHost/Dockerfile
    container_name: ks-apphost
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__KSummarized=Host=db;Database=ksummarized;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "5001:80"
      - "5000:443"
      - "17068:17068"
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /src/backend
        - action: sync
          path: ./frontend
          target: /src/frontend

  migrations:
    build:
      context: ./backend
      target: migrations
    container_name: ks-migrations
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__KSummarized=Host=db;Database=ksummarized;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

  db:
    image: postgres:14.0-alpine
    container_name: ks-database
    ports:
      - "5432:5432"
    volumes:
      - ks_postgresql:/var/lib/postgresql/data
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER}'"]
      interval: 3s
      timeout: 5s
      retries: 3

  keycloak:
    build:
      context: ./keycloak
    container_name: ks-keycloak
    command: start-dev --import-realm
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/imports/realms/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keycloak/imports/providers:/opt/keycloak/providers/
      - ./keycloak/themes/ksummarized:/opt/keycloak/themes/ksummarized/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # fake SMTP server to send emails
  smtp4dev:
    image: rnwood/smtp4dev:v3.1
    container_name: ks-smtp4dev
    ports:
      - "5050:80"
      - "25:25"
      - "143:143"
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

  redis:
    image: "redis:latest"
    container_name: ks-redis
    ports:
      - "6379:6379"

volumes:
  ks_postgresql:
  smtp4dev-data:
