name: "Inactive PR reminder"
on:
  schedule:
    # Run everyday at midnight
    - cron: "0 0 * * *"

jobs:
  inactive-pr-reminder:
    permissions:
      pull-requests: write
    if: github.repository == 'ksummarized/ksummarized.com'
    runs-on: ubuntu-latest
    steps:
      - uses: sojusan/github-action-reminder@v1
        with:
          reminder_message: "Two days have passed since the last activity. Please take care of this PR."
          inactivity_deadline_hours: 48
          default_users_to_notify: |
            @Sojusan
            @mtracewicz
