name: Lint and test - frontend

on:
  push:
  pull_request:
    branches: [master]
    paths:
      - "**.tsx"
      - "**.ts"

env:
  NODE_VERSION: "16"

jobs:
  build-and-test-frontend:
    name: list-and-test-${{matrix.os}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint
        working-directory: ./frontend
        run: npm run lint

      - name: Test
        working-directory: ./frontend
        run: npm run test
