name: Lint and test - frontend

on:
  push:
    paths:
      - "**.ts"
      - "**.tsx"
  pull_request:
    branches: [master]
    paths:
      - "**.ts"
      - "**.tsx"

env:
  NODE_VERSION: "20"

jobs:
  build-and-test-frontend:
    name: list-and-test-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Check licenses
        working-directory: ./frontend
        run: npm run license-checker-linux

      - name: Generate API client from OpenAPI schema
        working-directory: ./frontend
        run: npm run openapi-ts

      - name: Lint
        working-directory: ./frontend
        run: npm run lint

      - name: Test
        working-directory: ./frontend
        run: npm run test
