name: SonarCloud Frontend
on:
  push:
    branches:
      - master
    paths:
      - "**.ts"
      - "**.tsx"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.ts"
      - "**.tsx"
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
